language: node_js
node_js:
  - '0.10'
env:
  global:
  - CODECLIMATE_REPO_TOKEN=52b18ac355d35d8a0734d88b88ed093d98b72abfc082b97abcb9afeb41327b69 codeclimate-test-reporter < lcov.info
before_script:
  - npm install -g bower grunt-cli
  - bower install
after_script:
  - codeclimate-test-reporter < coverage/**/lcov.info